# main text of home
title: Anurup Naskar
title-bengali: 'অনুরূপ নস্কর' # optional
bio: Graduate Researcher in AI + Weather
description: MS Student in Computer Science (AI & ML) at New York University

# if it's an external image, update below
external-image: false
picture: assets/images/profile.jpeg
logo: assets/images/profile.jpeg

# site color theme: true=dark, false=light, auto=system
dark-theme: false

# If you want to include your CV, set to true and specify URL/source.
# resume: true
# resume-external: true
# resume-url: https://drive.google.com/file/d/REPLACE_WITH_YOUR_CV_PDF/view?usp=sharing

# Set this to your GitHub Pages URL
url: https://anurup123.github.io
# your url: https://USERNAME.github.io

permalink: /:title/

disqus:
  shortname: github
  categories: [blog, project]

# social accounts
# facebook: myfacebook
# twitter: mytwitter
# instagram: myinstagram
linkedin: anurup-naskar-0819972b6
github: anurup123
email: an4462@nyu.edu
google_scholar: https://scholar.google.com/citations?user=g_yV5gIAAAAJ&hl=en
cv_url: https://drive.google.com/file/d/1YtzEJ7VeXn8q959dlJsf4dMYmG3brRG3/view?usp=sharing

authors:
  anurup123:
    name: Anurup Naskar
    bio: Graduate Researcher in AI + Weather
    external-image: false
    picture: assets/images/profile.jpeg

# site width option: normal or large
width: normal

# enable/disable site features
about: true
# blog: true
weather: true

read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore: 
exclude:
  - archive
